ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
onlyBuiltDependencies:
  - ','
  - b
  - c
  - d
  - e
  - electron
  - esbuild
  - i
  - l
  - n
  - o
  - r
  - s
  - t
  - u
