version = 0.1

[default.global.parameters]
stack_name = "ui-dev-kit"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "ui-dev-kit"
parameter_overrides = "Environment=prod"